# Catppuccin Mocha Theme for Hyprtoolkit
background=0xff11111b
base=0xff1e1e2e
alternate_base=0xff181825
text=0xffcdd6f4
bright_text=0xffbac2de
accent=0xffb4befe
accent_secondary=0xffb4befe

font-size = 14
small-font-size = 12

icon-theme = Papirus-Dark

font-family = "JetBrainsMono Nerd Font"

