#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# tiling config
yabai -m config layout bsp

# padding/gap
yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5

# mouse
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config mouse_drop_action swap

# setup spaces
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 discord
setup_space 2 web
setup_space 3 code
setup_space 4 terminal
setup_space 5 
setup_space 6
setup_space 7
setup_space 8
setup_space 9

# do not manage
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^TinkerTool$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add label="Zen PIP" app="^Zen$" title="^(Picture-in-Picture)$" manage=off
yabai -m rule --add app="^Google Chrome$" title="^(Picture in Picture)$" manage=off
